#!/bin/bash -l
#SBATCH --cluster=wice
#SBATCH --account=llp_h_pds
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=72
#SBATCH --time=00:10:00
#SBATCH --error="%x.e%A"
#SBATCH --output="%x.o%A"

# Source dir
source /data/leuven/303/vsc30380/slurmhooks

module purge

module load CMake/3.26.3-GCCcore-12.3.0
module load GCC/12.3.0

for i in {1..10}
do
    echo "Running iteration $i"
    /data/leuven/303/vsc30380/kmeans_serial_reference --input mouse_500x2.csv \
    --output output_${i}.csv --repetitions 10 --k 3 --centroidtrace centroidtrace_${i}.csv \
    --trace clustertrace_${i}.csv --seed 1338
done
